server:
  port: 8089
spring: 
   datasource:
    url: jdbc:mysql://localhost:3306/linode_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true   application:    name: linodeservice
    
eureka:  client:    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
     defaultZone: http://localhost:8761/eureka/